/**
 * ตราลงสนาม — คนวิ่งที่อ่านเป็น ล ได้
 *
 * Two strokes and two circles, one stroke weight, round caps. The geometry is
 * measured from the reference artwork and generated by docs/build_logo.py;
 * change it there, not here, so the reference page and the app stay the same
 * mark.
 *
 * The mark is not square (120 × 86). Callers pass the height they want and
 * the width follows, so nobody has to remember the ratio.
 */
const ARMS = 'M33.5 51.5 C37 45 43.5 42.5 49 43.5 C60 46 72 63 86 69.5 C94 73 101.5 72.5 107.5 68';
const LEGS = 'M22 82 C27 77 31 79 34 83 C39.5 89 45 89.5 50.5 85 C57 79.5 61 73 64 68 L93.5 105 C96.5 108.5 100.5 107 102 101';
const STROKE = 9.2;

type Tone = 'brand' | 'lime' | 'ink' | 'white';

const toneColour: Record<Tone, string> = {
  brand: 'var(--color-brand-600)',
  /* Lime is line paint: only on brand-700 or darker, never on brand-500
     (2.32:1). The reference page records the ratios. */
  lime: 'var(--color-accent-500)',
  ink: 'var(--color-ink-900)',
  white: '#ffffff',
};

export function BrandMark({
  size = 32,
  tone = 'brand',
  className,
}: {
  /** Rendered height in px; width is derived. */
  size?: number;
  tone?: Tone;
  className?: string;
}) {
  const colour = toneColour[tone];
  return (
    <svg
      viewBox="0 32 120 86"
      width={Math.round((size * 120) / 86)}
      height={size}
      aria-hidden
      className={className}
    >
      <g fill="none" stroke={colour} strokeWidth={STROKE} strokeLinecap="round" strokeLinejoin="round">
        <path d={ARMS} />
        <path d={LEGS} />
        <circle cx="16.5" cy="85" r="5.6" />
      </g>
      <circle cx="79" cy="52" r="5.6" fill={colour} />
    </svg>
  );
}
